### ISSUE TITLE
2018.3

### ISSUE THREAD

**Issue by ledvinam** [Siccity/xNode#86]
This does not work in Unity 2018.3f1 OSX

#if UNITY_2018_3_OR_NEWER
                foreach (SettingsProvider settingsProvider in SettingsService.FetchSettingsProviders()) {
                    if (settingsProvider.name == "Node Editor") {
                        EditorPrefs.SetString("SettingsWindow_Preferences_current_provider", settingsProvider.settingsPath);
                        EditorApplication.ExecuteMenuItem("Edit/Preferences...");
                    }
                }
#else

**Comment by Siccity** [comment]
Try and see if #88 fixes it

**Comment by ledvinam** [comment]
Assets/Git/xNode/Editor/NodeEditorReflection.cs(117,42): error CS1061: 'SettingsProvider' does not contain a definition for 'name' and no extension method 'name' accepting a first argument of type 'SettingsProvider' could be found (are you missing a using directive or an assembly reference?)

**Comment by nostek** [comment]
Verified fix #88 working on 2018.3.0f2 on OSX Mojave and on Windows 10.

**Comment by ledvinam** [comment]
Not on my mojave and 2018.3f2. So where is the issue?

**Comment by nostek** [comment]
@ledvinam did you try to apply #88 on your branch? its not currently fixed in the master branch.

**Comment by Siccity** [comment]
Closed for inactivity. Feel free to open it again if the problem persists.
